services:
  - type: web
    name: anh-here-web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free

    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 8000

      - key: API_URL
        value: ${API_URL}

      - key: DB_HOST
        value: anh-here-db.internal

      - key: DB_PORT
        value: 3306

      - key: DB_NAME
        value: ${DB_NAME}

      - key: DB_USER
        value: ${DB_USER}

      - key: DB_PASSWORD
        value: ${DB_PASSWORD}

      - key: JWT_KEY
        value: ${JWT_KEY}

      - key: PEPPER
        value: ${PEPPER}

    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1


  - type: pserv
    name: anh-here-db
    env: docker
    image: mysql:8.4
    plan: free

    envVars:
      - key: MYSQL_DATABASE
        value: ${MYSQL_DATABASE}

      - key: MYSQL_USER
        value: ${MYSQL_USER}

      - key: MYSQL_PASSWORD
        value: ${MYSQL_PASSWORD}

      - key: MYSQL_ROOT_PASSWORD
        value: ${MYSQL_ROOT_PASSWORD}

    disk:
      name: mysql-data
      mountPath: /var/lib/mysql
      sizeGB: 5
